"""Tests for the Navidrome exporter's pure logic.

The resolver is the risky part: Navidrome's Subsonic `path` is synthesised from
tags and does NOT match the filesystem, so matching has to lean on title,
artist and duration instead. These pin that behaviour down without a Navidrome.
"""

import pytest

from app.export.navidrome import (
    MIN_ACCEPTABLE_SCORE,
    SubsonicError,
    _unwrap,
    build_comment,
    pick_best,
    score_candidate,
)


def track(title="Take Their Lives", artist="Kreator", ms=386_000, album=None):
    t = {"title": title, "artist_name": artist, "duration_ms": ms}
    if album:
        t["album_name"] = album
    return t


def song(title="Take Their Lives", artist="Kreator", duration=386, album="Flag of Hate", sid="a"):
    return {"id": sid, "title": title, "artist": artist, "duration": duration, "album": album}


# --- _unwrap: Subsonic fails INSIDE a 200 ---

def test_ok_response_is_unwrapped():
    body = {"subsonic-response": {"status": "ok", "version": "1.16.1"}}
    assert _unwrap(body)["version"] == "1.16.1"


def test_a_failed_response_raises_even_though_the_http_status_was_200():
    body = {
        "subsonic-response": {
            "status": "failed",
            "error": {"code": 40, "message": "Wrong username or password"},
        }
    }
    with pytest.raises(SubsonicError) as exc:
        _unwrap(body)
    assert exc.value.code == 40


def test_not_authorized_is_surfaced_not_swallowed():
    # Code 50 is what a non-admin gets for startScan; the same shape applies to
    # any operation the account is not allowed to perform.
    body = {"subsonic-response": {"status": "failed", "error": {"code": 50, "message": "nope"}}}
    with pytest.raises(SubsonicError):
        _unwrap(body)


# --- score_candidate ---

def test_a_different_title_scores_zero_whatever_else_agrees():
    assert score_candidate(track(), song(title="Pleasure to Kill")) == 0


def test_exact_title_artist_and_duration_scores_highest():
    assert score_candidate(track(), song()) == 90


def test_title_and_artist_alone_reach_the_acceptance_floor():
    # No duration on either side: still acceptable, just less certain.
    assert score_candidate(track(ms=0), song(duration=0)) >= MIN_ACCEPTABLE_SCORE


def test_a_wildly_different_runtime_is_penalised_as_another_recording():
    # Same title and artist, but a 9-minute live version.
    live = score_candidate(track(), song(duration=540))
    assert live < MIN_ACCEPTABLE_SCORE


def test_small_encoder_drift_is_tolerated():
    assert score_candidate(track(), song(duration=388)) >= MIN_ACCEPTABLE_SCORE


def test_case_and_whitespace_differences_do_not_break_a_match():
    assert score_candidate(track(), song(title="  take   THEIR lives ")) == 90


def test_matching_album_adds_confidence_when_we_know_it():
    with_album = score_candidate(track(album="Flag of Hate"), song())
    without = score_candidate(track(), song())
    assert with_album > without


def test_display_artist_is_used_when_artist_is_absent():
    candidate = {"id": "x", "title": "Take Their Lives", "displayArtist": "Kreator", "duration": 386}
    assert score_candidate(track(), candidate) == 90


def test_path_is_never_consulted():
    # A Subsonic `path` is tag-derived and does not match the real file. Feeding
    # a wildly wrong one must not change the score at all.
    misleading = song()
    misleading["path"] = "Totally/Different/Place.mp3"
    assert score_candidate(track(), misleading) == score_candidate(track(), song())


# --- pick_best ---

def test_nothing_above_the_floor_returns_none():
    assert pick_best(track(), [song(title="Something Else")]) is None


def test_no_candidates_at_all_returns_none():
    assert pick_best(track(), []) is None


def test_the_highest_scoring_candidate_wins():
    weak = song(artist="Some Covers Band", duration=300, sid="weak")
    strong = song(sid="strong")
    assert pick_best(track(), [weak, strong])["id"] == "strong"


def test_ties_break_deterministically_by_id():
    a = song(sid="aaa")
    b = song(sid="bbb")
    assert pick_best(track(), [b, a])["id"] == pick_best(track(), [a, b])["id"] == "aaa"


# --- build_comment: the field Jellyfin has no equivalent for ---

def test_comment_carries_the_prompt():
    assert '"doom for driving"' in build_comment("doom for driving", 20, 20)


def test_comment_reports_a_shortfall_honestly():
    assert "18 of 20" in build_comment("x", 20, 18)


def test_a_complete_push_does_not_claim_a_shortfall():
    assert "of" not in build_comment(None, 20, 20).split("—")[1]


def test_comment_survives_a_missing_prompt():
    assert build_comment(None, 5, 5).startswith("Generated by")
